version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - <PROJECT_DIR>/api:/usr/src/app
    links:
      - db

  agent:
    build: ./agent
    ports:
      - "5001:5001"
    volumes:
      - <PROJECT_DIR>/agent:/usr/src/app
    links:
      - db
      
  db:
    build: ./db
    volumes:
      - <DATABASE_DIR>:/data/db
    ports:
    # Expose port 27017 to the host, to give the rotary code access to the database 
      - "27017:27017"
